---
name: first workflow
on: workflow_dispatch
jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo 'hello $(hostname)!'
      - name:  Print goodbye
        run: echo 'Done, bye $(hostname)'
        
