name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      description: The result of the deployment operation
      value: ${{jobs.deploy.outcome}}
  # secrets:
  #   some-secrets:
  #     value: ${{secrets.GITHUB_TOKEN}}
  #     required: true
      

      
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with: 
          name: ${{inputs.artifact-name}}
      - name: List files
        run: ls
      - name: Output Information
        run: echo 'Deploying & Uploading...'
      - name: Set result output
        id: set-result
        run: |
          echo 'step-result=success' >> $GITHUB_OUTPUT